yarn run build
cp CNAME ./docs/.vuepress/dist/
echo "## Autogenerated by Vuepress. Code is on the 'dev' branch" > ./docs/.vuepress/dist/README.md
$(npm bin)/push-dir --dir=./docs/.vuepress/dist/ --branch=master