yarn run lint && yarn run generate
cp CNAME dist/
echo '# Autogenerated by Nuxt. Code is on `dev` branch' | cat - README.md > temp && mv temp dist/README.md
$(npm bin)/push-dir --dir=dist --branch=master --cleanup